export const GROCERY_ITEMS: string[] = [
  "aachi fish masala",
  "aam papad",
  "aamras",
  "aar maach",
  "achari masala",
  "achari mayo",
  "acorn squash",
  "active dry yeast",
  "adobo sauce",
  "agar agar",
  "agathi keerai",
  "ajwain",
  "alfalfa powder",
  "all purpose flour",
  "all spice powder",
  "almond",
  "almond butter",
  "almond meal",
  "almond milk",
  "almond oil",
  "aloo bhujia",
  "aloo tikki",
  "alu bukhara",
  "amaranth leaves",
  "amaranth seeds",
  "amchur",
  "amchur powder",
  "anardana powder",
  "aniseed",
  "apple",
  "apple cider vinegar",
  "apple juice",
  "apple vodka",
  "apricots",
  "arabic leaves",
  "arabica",
  "arbi",
  "arborio rice",
  "arhar dal",
  "arisithipli",
  "arrowroot flour",
  "artichokes",
  "arugula leaves",
  "asafoetida",
  "ash gourd",
  "ash gourd chips",
  "asparagus",
  "assam tea leaves",
  "aubergine",
  "avarekai",
  "avarekalu / lilva beans",
  "avocado",
  "avrekalu",
  "baby corn",
  "baby potatoes",
  "baby spinach",
  "bacon",
  "bacon strips",
  "badam",
  "badi",
  "badi hari mirch",
  "bagel",
  "baguette",
  "baileys irish cream",
  "bajra",
  "bajra dosa batter",
  "bajra flour",
  "baked beans",
  "baking powder",
  "baking soda",
  "balsamic vinegar",
  "bamboo shoots",
  "banana",
  "banana flower",
  "banana leaf",
  "banana leaves",
  "banana stem",
  "barbeque masala",
  "barbeque sauce",
  "barley",
  "barnyard millet",
  "basa fish",
  "basella",
  "basil",
  "basil leaves",
  "basil powder",
  "basmati rice",
  "bathua leaves",
  "bay leaf",
  "bay leaves",
  "bc belle bhat powder",
  "bean paste",
  "bean sprouts",
  "beef",
  "beetroot",
  "beetroot greens",
  "beetroot juice",
  "bengal",
  "ber",
  "betel leaves",
  "bhaja masala",
  "bhakarwdis",
  "bhang paste",
  "bhetki fish",
  "bhindi",
  "bhindi/okra/vendaikkai",
  "big",
  "bimbla",
  "biryani masala",
  "biryani masala powder",
  "bisi bele bhat spice powder",
  "bisleri fonzo",
  "bitter gourd",
  "bitter sweet chocolate",
  "black",
  "black beans",
  "black cardamom",
  "black chili powder",
  "black currant ice cream",
  "black eyed beans",
  "black grapes",
  "black olives",
  "black pepper",
  "black pepper powder",
  "black peppercorn",
  "black raisins",
  "black rice",
  "black salt",
  "black salt or rock salt",
  "black sesame seeds",
  "black tea",
  "black urad dal",
  "blackberries",
  "blanched tomatoes",
  "blueberries",
  "bocconcini cheese",
  "boiled egg",
  "boiled peanuts",
  "bok choy",
  "boneless chicken",
  "boondi",
  "botis",
  "bottle gourd",
  "bourbon",
  "bourbon biscuits",
  "brahmi leaves",
  "brandy",
  "bread",
  "bread crumbs",
  "bread loaf",
  "brie cheese",
  "brinjal",
  "britannia cheese block",
  "britannia cheese cubes",
  "britannia cheese slice",
  "britannia cheese spread",
  "britannia cheezza",
  "britannia cream cheese",
  "broccoli",
  "broken raw rice",
  "broken wheat",
  "brown bread",
  "brown cardamom",
  "brown rice",
  "brown sugar",
  "brussel sprouts",
  "buckwheat flour",
  "bud long",
  "bulgur wheat",
  "burger buns",
  "butter",
  "buttermilk",
  "butternut squash",
  "butterscotch chips",
  "butterscotch ice cream",
  "button mushroom",
  "byadagi dried chillies",
  "cabbage",
  "cabbage leaves",
  "cajun spice mix",
  "cake mix",
  "can bamboo shots",
  "can condensed milk",
  "candied orange peel",
  "cane sugar",
  "canned beans",
  "canned black beans",
  "canned cherries",
  "canned tuna",
  "canola oil",
  "cape gooseberries",
  "capers",
  "capsicum",
  "caramel sauce",
  "caramelized onions",
  "cardamom",
  "cardamom crush",
  "cardamom pods/seeds",
  "cardamom powder",
  "carp fish",
  "carrot",
  "carrot cake",
  "cashew",
  "cashew nuts",
  "cashmere red chilli powder",
  "cassia",
  "cast coriander",
  "cast curry leaves",
  "caster sugar",
  "castor sugar",
  "cauliflower",
  "cauliflower leaves",
  "cayenne",
  "cayenne pepper",
  "celery",
  "chaat masala powder",
  "chai masala",
  "chakra flowers",
  "chakundar",
  "chamomile tea",
  "champagne",
  "chana dal",
  "chana dal (bengal",
  "chana masala powder",
  "chana stock",
  "chandis work",
  "char magaz",
  "charcoal",
  "chawla pods",
  "chayote",
  "cheddar cheese",
  "cheese",
  "cheese cubes",
  "cheese slices",
  "cheese spread",
  "chenna",
  "cherry tomatoes",
  "chhedar cheese",
  "chia seeds",
  "chicken",
  "chicken breast",
  "chicken drumstick",
  "chicken ham",
  "chicken legs",
  "chicken masala",
  "chicken sausage",
  "chicken stock",
  "chicken thigh",
  "chicken wings",
  "chickpea lentil",
  "chickpeas spices",
  "chikki",
  "chikoo",
  "chilled butter",
  "chilled water",
  "chilli oil",
  "chilli vinegar",
  "chilly flax",
  "chinese",
  "chinese cabbage",
  "chinese potato",
  "chipotle chillies / peppers",
  "chipotle peppers",
  "chipotle sauce",
  "chironji",
  "chiroti rava",
  "chisemis",
  "chives",
  "choco thins",
  "chocolate bar",
  "chocolate cake",
  "chocolate chips",
  "chocolate ganache",
  "chocolate ice cream",
  "chocolate pearls",
  "chocolate sauce",
  "chocolate shavings",
  "chocolate wafers",
  "chow chow",
  "chyawanprash",
  "ciabatta bread",
  "cinnamon",
  "cinnamon powder",
  "cinnamon stick",
  "citric acid crystals",
  "clamps",
  "clams",
  "classic alfredo pasta sauce",
  "classic mayonnaise",
  "cloves",
  "cluster fig",
  "coca cola",
  "cocoa powder",
  "coconut",
  "coconut cream",
  "coconut flour",
  "coconut milk",
  "coconut oil",
  "coconut powder",
  "coconut sugar",
  "coconut yogurt",
  "coffee decoction",
  "cold water",
  "colocasia leaves",
  "colocasia root",
  "colostrum",
  "conchiglie pasta",
  "condensed milk",
  "confectioners sugar",
  "cooked rice",
  "cooking soda",
  "coriander",
  "coriander leaves",
  "coriander powder",
  "coriander seeds",
  "corn chips",
  "corn cob",
  "corn flakes",
  "corn flour",
  "corn flour tortilla",
  "corn kernels",
  "corn meal",
  "cottage cheese",
  "cotton threads",
  "couscous",
  "cowpea",
  "cowpea pods",
  "crab",
  "crackers",
  "cranberries",
  "cranberry juice",
  "cream",
  "cream of tartar",
  "crepes",
  "crush",
  "crushed ice",
  "crusty bread log",
  "cucumber",
  "cumene seeds",
  "cumin",
  "cumin powder",
  "cumin seeds",
  "curd",
  "curd vada",
  "curry",
  "curry garlic",
  "curry leaf",
  "curry leaves",
  "curry powder",
  "custard apple",
  "custard powder",
  "cut",
  "cut lemon",
  "dabur homemade coconut milk",
  "dabur homemade tamarind paste",
  "dagad phool",
  "dal stock",
  "dal sugar",
  "dark chocolate",
  "dark chocolate chips",
  "dark soy sauce",
  "date syrup",
  "dates",
  "decorative sugar",
  "del monte black olives",
  "del monte cheesy dip",
  "del monte cheesy garlic mayo",
  "del monte chifferi rigati pasta",
  "del monte farfalle pasta",
  "del monte green olives",
  "del monte mint mayo",
  "del monte penne rigate pasta",
  "del monte sandwich spread",
  "del monte spaghetti pasta",
  "del monte tandoori mayo",
  "del monte tartare dip",
  "del monte tricolour spirali pasta",
  "del monte whole corn kernels",
  "dessicated coconut",
  "dhansak masala",
  "digestive biscuit",
  "dijon mustard",
  "dill leaves",
  "dosa rice",
  "double beans",
  "double cream",
  "dragon fruit",
  "drain the water",
  "dried anardana seeds",
  "dried basil leaves",
  "dried chamomile",
  "dried figs",
  "dried green peas",
  "dried mushrooms",
  "dried neem flowers",
  "dried oregano",
  "dried raspberries",
  "dried red chilli",
  "dried rose petals",
  "dried shrimps",
  "dried thyme leaves",
  "dried turmeric",
  "dried yellow/white peas",
  "drumstick",
  "drumstick leaves",
  "dry beans",
  "dry coconut",
  "dry dates powder",
  "dry fruits",
  "dry ginger powder",
  "dry green mango",
  "dry kashmiri chillies",
  "dry kashmiri peppers",
  "dry mix herbs",
  "dry poppy",
  "dry red chilli",
  "dry red peppers",
  "dry white wine",
  "edible camphor",
  "edible silver foil/leaf",
  "egg",
  "egg noodles",
  "egg white",
  "egg yolks",
  "eggless mayonnaise",
  "eggplant",
  "elaichi",
  "elbow pasta",
  "elephant yam",
  "emami rice bran oil",
  "english cucumber",
  "enos fruit salt",
  "espresso powder",
  "extra virgin olive oil",
  "extract of natural bourbon vanilla",
  "falsa",
  "farsan",
  "fennel",
  "fennel bulb",
  "fennel leaves",
  "fennel powder",
  "fennel seeds",
  "fenugreek",
  "fenugreek seeds",
  "feta cheese",
  "fettuccine pasta",
  "few basil leaves",
  "few branch green coriander",
  "few cashew nuts",
  "few coriander leaves",
  "few curry leaves",
  "few dill leaves",
  "few ice cubes",
  "few mint leaves",
  "few pistachios",
  "few roasted peanuts",
  "few saffron strands",
  "few sprig basil leaves",
  "few sprig coriander leaves",
  "few sprig fresh thyme leaves",
  "few sprig mint leaves",
  "few sprig parsley leaves",
  "few sprig purple basil",
  "few spring onion",
  "few whole black peppercorns",
  "figaro pure olive oil",
  "figs",
  "filter coffee powder",
  "fish",
  "fish fillet",
  "fish sauce",
  "fistful green peas",
  "fl oz britannia cream cheese",
  "fl oz condensed milk",
  "fl oz evaporated milk",
  "flat green beans",
  "flaxmeal egg replacer",
  "flaxseed",
  "flaxseed powder",
  "flour",
  "flower cabbage",
  "food color",
  "foxtail millet",
  "foxtail millet flour",
  "french beans",
  "french bread",
  "french fries",
  "french loaf",
  "fresh cherries",
  "fresh coconut",
  "fresh cream",
  "fresh figs",
  "fresh fruits",
  "fresh green chickpeas",
  "fresh green toor dal",
  "fresh herbs",
  "fresh orange juice",
  "fresh oregano",
  "fresh pomegranate fruit kernels",
  "fresh raspberries",
  "fresh red chilli",
  "fresh rose petals",
  "fresh thyme leaves",
  "fresh turmeric root",
  "fresno pepper",
  "fried bread cubes",
  "fried rice",
  "fruit",
  "galangal",
  "garam masala powder",
  "garlic",
  "garlic butter",
  "garlic chutney",
  "garlic powder",
  "garlic salt",
  "gawar phali",
  "gelatin",
  "ghee",
  "gherkins",
  "ghost chilli peppers",
  "gilka",
  "gingelly oil",
  "ginger",
  "ginger cookies",
  "ginger garlic paste",
  "ginger juice",
  "ginger paste",
  "ginger powder",
  "ginger teriyaki sauce",
  "glazed cherries",
  "gleppino",
  "gms cheese",
  "gms cottage cheese",
  "gms fenugreek",
  "gms hen",
  "goat cheese",
  "gobi",
  "gochujang",
  "goda masala",
  "goji berries",
  "golden harvest sona masuri rice",
  "gond",
  "gondhoraj lebu juice",
  "gondhoraj lebu lemon",
  "gongura",
  "gongura leaves",
  "good",
  "good powder done",
  "goond",
  "gouda cheese",
  "gourd",
  "govind bhog rice",
  "graham cracker crumbs",
  "grand marnier",
  "granola",
  "granulated sugar",
  "grape juice",
  "grapefruit",
  "great northern beans",
  "green amaranth leaves",
  "green apple",
  "green beans",
  "green bell pepper",
  "green brinjal",
  "green capsicum",
  "green cardamom",
  "green chawli beans",
  "green chilli",
  "green chilli paste",
  "green chilli sauce",
  "green chutney",
  "green coffee beans",
  "green coriander",
  "green food colour",
  "green grapes",
  "green moong dal",
  "green moong sprouts",
  "green olives",
  "green onion",
  "green onion leaves",
  "green peas",
  "green peppers",
  "green romaine lettuce",
  "green seedless grapes",
  "green tea leaves",
  "green tur dal",
  "green zucchini",
  "greens",
  "grind",
  "groundnut",
  "groundnut oil",
  "groundnut powder",
  "gruyere cheese",
  "guacamole",
  "guava",
  "guava juice",
  "guava puree",
  "gulab jamun",
  "gulab jamun mix",
  "gulkand",
  "gunde",
  "guntur dried chillies",
  "guntur red chillies",
  "gwar pods",
  "hakka noodles",
  "halloumi cheese",
  "hara chana",
  "hard taco shells",
  "harissa paste",
  "hariyali chicken tikka",
  "hash browns",
  "hazelnut",
  "hazelnut meal",
  "health mix",
  "heart leaves",
  "heavy whipping cream",
  "herb butter",
  "herring fish steaks",
  "hilsa fish",
  "hog plum",
  "homemade basil pesto",
  "homemade hoisin sauce",
  "homemade hummus",
  "homemade mole sauce",
  "homemade pizza and pasta sauce",
  "homemade pizza dough",
  "homemade tomato puree",
  "homemade whole wheat khakras",
  "honey",
  "honey dew melon",
  "horlicks",
  "horse",
  "horse powder",
  "hot dog bread",
  "hot masala powder",
  "hot water",
  "hulled wheat",
  "hung curd",
  "ice",
  "ice apple",
  "ice cream",
  "ice cream cone",
  "ice cubes",
  "iceberg lettuce",
  "icing sugar",
  "idiyappam",
  "idli",
  "idli dosa batter",
  "idli dosa mixture",
  "idli dosa podi",
  "idli rice",
  "indian borage",
  "indian butter fish",
  "ino fruit salt",
  "instant coffee powder",
  "instant dosa mix powder",
  "instant oats",
  "italian bread",
  "italian seasoning",
  "jackfruit",
  "jackfruit raw",
  "jackfruit ripe",
  "jackfruit seeds",
  "jaggery",
  "jal jeera powder",
  "jalepino",
  "jam",
  "jamun",
  "japanese eggplant",
  "jasmine rice",
  "jawla fish",
  "jello",
  "jelly mix",
  "jowar flour",
  "jowar seeds",
  "kababchini",
  "kabuli chana",
  "kachampuli",
  "kachri",
  "kaddu",
  "kadhi leaves",
  "kadhi masala",
  "kaffir lime leaves",
  "kala chana",
  "kala jeera",
  "kale",
  "kali urad dal",
  "kalmatta olives",
  "kalonji",
  "kalonji seeds",
  "kalpasi flower",
  "kalpasi leaves",
  "kandathipli",
  "kapok bud",
  "karela",
  "kashmiri dry red chilli",
  "kashmiri masala powder",
  "kashmiri rajma",
  "kashmiri red chilli",
  "kashmiri red chilli powder",
  "kasoori fenugreek",
  "kasoori methi",
  "kasundi mustard sauce",
  "kasuri methi",
  "kataifi dough",
  "kebab masala",
  "kenua",
  "ker",
  "kerala matta rice",
  "kesar milk masala",
  "kewra essence",
  "kewra water",
  "khaman dhokla",
  "khichdi",
  "khichdi/pongal",
  "khoya",
  "khurchan",
  "khus khus",
  "khus syrup",
  "khuskhus",
  "kidney beans",
  "kilo",
  "kimchi",
  "king fish",
  "kinua",
  "kitkat bars",
  "kiwi",
  "knol khol",
  "knol khol leaves",
  "knoll knoll leaves",
  "kodo millet",
  "kohl rabi",
  "kokum",
  "kolhapuri khanda lasun masala",
  "kolhapuri masala",
  "koli masala",
  "kosher salt",
  "kulith dal",
  "kunafa dough",
  "kunafa pastry",
  "lady fish",
  "ladyfinger",
  "lahsun ki chutney",
  "lamb",
  "lamb ribs",
  "lamb trotters",
  "lasagna sheets",
  "lavang",
  "lavender flowers",
  "leaf",
  "lebanese cucumber",
  "leek",
  "leftover roti",
  "lemon",
  "lemon glaze",
  "lemon juice",
  "lemon pound cake",
  "lemon wedges",
  "lemon zest",
  "lemongrass",
  "lentil",
  "lentil sugar",
  "lentil water",
  "lettuce",
  "lettuce leaves",
  "light soy sauce",
  "lima beans",
  "lime wedges",
  "linguine pasta",
  "little",
  "loaf french bread",
  "long",
  "long garlic",
  "long green brinjal",
  "long long",
  "long pepper",
  "long string bean",
  "loose leaf tea",
  "lotus stem",
  "lukewarm water",
  "lychee",
  "m\u0026mâ€™s chocolate candies",
  "macaroni",
  "macaroni pasta",
  "mace",
  "mace powder",
  "mackerel fish",
  "maharashtrian goda masala",
  "maida",
  "maize flour",
  "make",
  "makhana",
  "makki ka atta",
  "malabar spinach leaves",
  "malt vinegar",
  "maltesers",
  "malwani masala",
  "manathakkali kai vathal",
  "manathakkali keerai",
  "mandi",
  "mangalorean cucumber",
  "mango",
  "mango ginger",
  "mango juice",
  "mango pickle",
  "mango powder",
  "mango powder powder",
  "mango pulp",
  "mango shrikhand",
  "mangodi",
  "maple syrup",
  "marie biscuit",
  "masauras",
  "mascarpone cheese",
  "mash",
  "masoor dal",
  "matcha powder",
  "mayo",
  "meat masala",
  "medu vada",
  "melon seeds",
  "mess",
  "methi leaves",
  "methi powder",
  "methi seeds",
  "mexican seasoning",
  "milk",
  "milk chocolate",
  "milk powder",
  "millet flour",
  "mini pita breads",
  "mint",
  "mint finely chopped",
  "mint leaves",
  "mint powder",
  "mint rice",
  "mixed beans",
  "mixed berries",
  "mixed dry fruits",
  "mixed fruits",
  "mixed greens",
  "mixed herbs",
  "mixed masala",
  "mixed millets",
  "mixed nuts",
  "mixed spices",
  "mixed sprouts",
  "mixed vegetables",
  "momos",
  "mooli ke patte",
  "mooli/ mullangi",
  "mor milagai",
  "moth dal",
  "moth sprouts",
  "motichoor ladoos",
  "mozzarella cheese",
  "muesli",
  "mughlai meetha attar",
  "multigrain digestive biscuits",
  "multigrain digestive oat biscuits",
  "multigrain digestive ragi biscuits",
  "multigrain flour",
  "musk melon",
  "mussels",
  "mustard",
  "mustard flowers",
  "mustard greens",
  "mustard oil",
  "mustard powder",
  "mustard sauce",
  "mustard seeds",
  "mutton",
  "mutton kheema",
  "mutton legs",
  "mutton liver",
  "naan",
  "nachos",
  "nagkesar/cassia buds",
  "nandos peri peri chicken marinade",
  "nandos peri peri chicken sauce",
  "napa cabbage",
  "neem leaves",
  "nendra pazham banana",
  "nilla cookies",
  "nolen gur",
  "nuggets coriander",
  "nuggets curry leaves",
  "nutella spread",
  "nutmeg",
  "nutmeg powder",
  "nutralite cheesy garlic mayo",
  "nutralite classic spread",
  "nutralite garlic \u0026 oregano spread",
  "oat bran",
  "oatmeal",
  "oats",
  "oats dosa batter",
  "oats flour",
  "of aa",
  "of arhar dal",
  "of batua",
  "of cardamom powder",
  "of casmis",
  "of chicken",
  "of chickpea",
  "of chickpea chana or chickpeas",
  "of chickpea chickpea or chickpeas",
  "of coriander",
  "of cottage cheese",
  "of curry leaves",
  "of fenugreek seeds",
  "of feta cheese",
  "of garlic",
  "of green coriander",
  "of kalonji seeds",
  "of lemon juice",
  "of mint",
  "of mutton",
  "of olive oil",
  "of red chili powder",
  "of strawberries",
  "of suran",
  "of thyme leaves",
  "of trumpet",
  "of tur dal",
  "of water",
  "oil wise",
  "okra",
  "olive oil",
  "onion",
  "onion powder",
  "onion sambar ones",
  "orange",
  "orange bell pepper",
  "orange blossom water",
  "orange color",
  "orange essence",
  "orange liquor",
  "orange marmalade jam",
  "orange peel",
  "orange pulp",
  "orange zest",
  "oregano",
  "oreo biscuits",
  "oyster sauce",
  "oysters",
  "pabda fish",
  "pachranga pickle",
  "palm fruit",
  "palm jaggery",
  "palm sugar",
  "panch four masala",
  "panch phoran masala",
  "panchon masala",
  "pandan leaf",
  "paneer",
  "pani puris",
  "panini bread",
  "papad",
  "papad khar",
  "papaya",
  "papaya juice",
  "papdi puri",
  "paprika powder",
  "parcel",
  "parcels",
  "parmesan cheese",
  "parmigiano reggiano cheese",
  "parseley",
  "parshe",
  "parsley",
  "parsley leaves",
  "parsnip",
  "parwal",
  "passion fruit",
  "pasta",
  "pastry dough",
  "pav bhaji masala",
  "pav buns",
  "peaches",
  "peanut",
  "peanut butter",
  "peanut oil",
  "peanuts",
  "pearl onions",
  "pears",
  "pecans",
  "peel",
  "peel and chop",
  "peel and then grind",
  "peepramul powder",
  "penne pasta",
  "pepper powder",
  "peppermint",
  "peruvian beans",
  "pheni",
  "phool makhana",
  "phulka",
  "phyllo dough",
  "phyllo sheets",
  "phyllo tartlet",
  "pickle",
  "pickle masala",
  "pickled jalapenos",
  "pickled onions",
  "pigeonpea",
  "pimiento stuffed green olives",
  "pine nuts",
  "pineapple",
  "pineapple essence",
  "pineapple juice",
  "pink flesh dragon fruit/pitaya",
  "pink food colour",
  "pink masoor dal",
  "pinto beans",
  "pirandai",
  "pistachio extract",
  "pistachios",
  "pita chips",
  "pita saga",
  "pitted cherries",
  "pizza base",
  "pizza seasoning",
  "plantain stem",
  "plum",
  "plum rose fruit",
  "plum sauce",
  "plums",
  "poblano chillies",
  "poha",
  "pohala fish",
  "pointed gourd",
  "polenta",
  "pomegranate",
  "pomegranate juice",
  "pomegranate molasses",
  "pomegranate powder",
  "pomegranate sauce",
  "pomfret fish",
  "poppy poppy",
  "poppy poppy seeds",
  "poppy seeds",
  "pork belly",
  "pork sausage",
  "portobello mushrooms",
  "potato",
  "potato masala",
  "potatoes",
  "powder",
  "prawns",
  "preserved pineapple",
  "processed cheese",
  "prune",
  "prunes",
  "puff pastry sheet",
  "puffed rice",
  "puliodarai powder",
  "pumpkin",
  "pumpkin flowers",
  "pumpkin leaves",
  "pumpkin pasta sauce",
  "pumpkin pie spice",
  "pumpkin puree",
  "pumpkin seeds",
  "punjabi aloo samosa",
  "punjabi style mango pickle",
  "puris used for pani puri",
  "purple cabbage",
  "purple carrots",
  "purple yam",
  "quail eggs",
  "quinoa",
  "quinoa flour",
  "rabdi",
  "rabodi",
  "rabri",
  "radish",
  "radish leaves",
  "radishes",
  "ragi cookies",
  "ragi dosa batter",
  "ragi flour",
  "ragi rava",
  "ragi seeds",
  "raisins",
  "raita masala",
  "rajgira flour",
  "rajma",
  "ranch sauce",
  "ras el hanout spice blend",
  "rasam powder",
  "rasgulla",
  "rasgulla syrup",
  "ratan jot",
  "raw banana",
  "raw banana peel",
  "raw mango",
  "raw mangoes",
  "raw papaya",
  "raw peanuts",
  "raw rice",
  "reacheado masala",
  "recipe all purpose pie crust",
  "recipe chocolate ganache",
  "recipe pastry dough",
  "red amaranth leaves",
  "red baby radish",
  "red bell pepper",
  "red cabbage",
  "red chilli",
  "red chilli flakes",
  "red chilli flax",
  "red chilli paste",
  "red chilli powder",
  "red chilli sauce",
  "red food color",
  "red grapes",
  "red matta rice",
  "red mustard seeds",
  "red onion",
  "red poha",
  "red radish",
  "red romaine lettuce",
  "red seedless grapes",
  "red wine",
  "red wine vinaigrette",
  "red yellow and green bell peppers",
  "red yellow or green bell pepper",
  "refried beans",
  "reserved water",
  "rice",
  "rice ada",
  "rice flour",
  "rice noodles",
  "rice paper rolls",
  "rice puttu",
  "rice rava",
  "rice vermicelli noodles",
  "rice vinegar",
  "rice water",
  "rice wine vinegar",
  "ricotta cheese",
  "ridge gourd",
  "ridge gourd skin",
  "ripe bananas",
  "roasted peanuts",
  "roasted tomato pasta sauce",
  "rock salt",
  "rocket leaves",
  "rohu fish",
  "rolled oats",
  "rolled oats or instant oats",
  "rooh afza sharbat",
  "roomali roti",
  "rose essence",
  "rose leaves",
  "rose petals",
  "rose syrup",
  "rose water",
  "rosemary",
  "roti",
  "round flower",
  "route pasta",
  "rum",
  "rusk",
  "rye",
  "rye bread",
  "s baking powder",
  "s sesame seeds",
  "sabudana",
  "sabza seeds",
  "saffron",
  "saffron strands",
  "sage",
  "salad leaves",
  "salmon fillet",
  "salt and pepper",
  "salt to taste",
  "salted butter",
  "sama flour",
  "sambal oelek",
  "sambal paste",
  "sambar powder",
  "samosas",
  "samvat rice",
  "sardine fish",
  "sarsaparilla",
  "sauerkraut",
  "save",
  "schezwan sauce",
  "scoop vanilla ice cream",
  "sea salt",
  "seaweed sheets",
  "seer fish",
  "seeraga samba rice",
  "semia",
  "semiya",
  "semolina",
  "serrano pepper",
  "sesame",
  "sesame oil",
  "sesame powder",
  "sesame seeds",
  "sesame seeds oil",
  "sev",
  "shallot",
  "shallots",
  "shark fish",
  "shell pasta",
  "sherry",
  "shiitake mushrooms",
  "shortbread cookies",
  "shrikhand",
  "shrimps",
  "sichuan peppercorns",
  "silver balls",
  "singhade",
  "singoda flour",
  "slider bun",
  "slivered almonds",
  "small",
  "small potatoes",
  "snake gourd",
  "soba noodles",
  "soda",
  "soft taco shells",
  "sooji",
  "sorghum",
  "sorrel leaves",
  "soup buns",
  "sour cream",
  "sourdough bread",
  "soy flour",
  "soy granules",
  "soya chaap",
  "soya chunks",
  "soya milk",
  "soya sauce",
  "soybeans",
  "spaghetti pasta",
  "spinach",
  "spinach basil sauce",
  "spinach leaves",
  "spirali pasta",
  "spirulina",
  "split methi seeds",
  "split mustard seeds",
  "sponge cake slice",
  "spoon",
  "spoon black pepper powder",
  "spoon black urad dal",
  "spoon chaat masala powder",
  "spoon coconut",
  "spoon coriander leaves",
  "spoon coriander powder",
  "spoon coriander seeds",
  "spoon cumin powder",
  "spoon cumin seeds",
  "spoon curry leaves",
  "spoon garam masala powder",
  "spoon lemon juice",
  "spoon nutmeg powder",
  "spoon oil",
  "spoon peanut powder",
  "spoon peanuts",
  "spoon red chilli powder",
  "spoon roasted tomato sauce",
  "spoon rye",
  "spoon turmeric powder",
  "sprig",
  "spring onion",
  "spring onion bulbs",
  "spring onion greens",
  "spring roll wrappers",
  "sprite",
  "sprouted moong",
  "squid",
  "sriracha sauce",
  "ssp asafoetida",
  "star anees",
  "star anise",
  "star fruit",
  "stock celery",
  "stock green coriander",
  "stone flower",
  "strawberries",
  "strawberry",
  "strawberry cake",
  "strawberry compote",
  "strawberry jam",
  "strawberry wafers",
  "submarine bread",
  "sugar snap peas",
  "sugar syrup",
  "sugarcane juice",
  "sultanas",
  "sumac",
  "summac",
  "summer salad",
  "sun dried tomato pesto",
  "sundakkai",
  "sundried tomatoes",
  "sunflower oil",
  "sunflower seeds",
  "suran",
  "sweet and spicy red chilli sauce",
  "sweet boondi",
  "sweet chutney",
  "sweet corn",
  "sweet piquantÃ© pepper",
  "sweet potato",
  "sweet potatoes",
  "sweetened coconut flakes",
  "swiss cheese",
  "tabasco original",
  "taco seasoning",
  "tagliatelle pasta",
  "tahini",
  "take out",
  "tamarind",
  "tamarind chutney",
  "tamarind paste",
  "tamarind sauce",
  "tamarind water",
  "tandoori chicken masala",
  "tandoori masala",
  "tapioca flour",
  "tapioca root",
  "tarragon",
  "tava paratha",
  "tawa paratha",
  "tea",
  "tea bags",
  "tea leaf",
  "tea leaves",
  "tea monk bodh second flush black tea",
  "tea monk oolong tea",
  "tea monk seiki peppermint green tea",
  "tender coconut meat",
  "tender coconut water",
  "tender mango",
  "tequila",
  "teriyaki sauce",
  "tetley long leaf green tea",
  "thai basil leaves",
  "thai green curry paste",
  "thai jasmine rice",
  "thai red chilli",
  "thai red curry paste",
  "thai sweet chilli sauce",
  "thai yellow curry paste",
  "thandai masala",
  "thandai powder",
  "thandai syrup",
  "thattai",
  "thin semiya",
  "this galangal",
  "thonnai",
  "thyme leaves",
  "tighten",
  "tighten it",
  "tikka masala",
  "tinda",
  "tindora",
  "to / s mint leaves",
  "tofu",
  "tomatillo",
  "tomato",
  "tomato basil pasta sauce",
  "tomato ketchup",
  "tomato puree",
  "tomato salsa",
  "tomatoes",
  "toothpicks",
  "tortilla",
  "tortillas",
  "triple sec",
  "trumpet",
  "tulsi",
  "tur dal",
  "turkey berries",
  "turmeric",
  "turmeric leaves",
  "turmeric powder",
  "turnips",
  "tutti frutti",
  "tutti frutti ice cream",
  "tzatziki",
  "udon noodles",
  "udupi sambar powder",
  "uncooked bananas",
  "urad dal",
  "urad dal flour",
  "urad dal papad",
  "vangi bath powder",
  "vanilla custard",
  "vanilla extract",
  "vanilla ice cream",
  "veeba burger mayonnaise",
  "veeba carrot cucumber sandwich spread",
  "veeba harissa sauce",
  "veeba pasta sauce",
  "veeba pizza \u0026 pasta sauce",
  "veeba sriracha sauce",
  "veeba sweet chilli sauce",
  "veg hakka noodles",
  "vegetable stock",
  "vellai poosanikai",
  "vinegar",
  "vivatta maida",
  "walking catfish",
  "walnuts",
  "wangi bhat powder",
  "watermelon",
  "watermelon rind",
  "watermelon seeds",
  "weet bix",
  "wheat berries/ whole wheat",
  "wheat bran",
  "wheat bread crumbs",
  "wheat brown bread",
  "wheat flour",
  "wheat flour tortilla",
  "wheat germ",
  "wheat grass",
  "wheat grass powder",
  "wheat noodles",
  "wheat oatmeal cookies",
  "wheat pita bread",
  "wheat pizza dough",
  "wheat tawa paratha",
  "whiskey",
  "white bacardi rum",
  "white beans",
  "white broad beans",
  "white butter",
  "white chocolate",
  "white hibiscus leaves",
  "white onion",
  "white pepper powder",
  "white urad dal",
  "white urad lentils",
  "white vinegar",
  "white wine vinegar",
  "wild rice",
  "wonton wraps",
  "wood apple",
  "worcestershire sauce",
  "yakisoba noodles",
  "yam",
  "yellow bell pepper",
  "yellow fenugreek seeds",
  "yellow food colour",
  "yellow moong dal",
  "yellow mustard seeds",
  "yellow squash",
  "yellow zucchini",
  "yogurt",
  "zaatar",
  "ziti pasta",
  "zucchini",
  "1/2 inch cinnamon stick",
];
